CPS-IT/frontend-asset-handler

.github/dependabot.yml
The target branch is `develop`, since we're using Git Flow.
=> [BUGFIX] Fix target branch in Dependabot PRs

src/Command/InitConfigCommand.php
After some major rewrites concerning asset definitions, the margins between outputs from the interactive `init` command were not aligned. This is now fixed.
=> [BUGFIX] Align margins in interactive `init` command execution

docs/migration.md
With this PR, some more breaking changes are added to the migration guide.
=> [DOCS] Add missing instructions to the migration guide

src/Asset/Environment/Transformer/PassthroughTransformer.php, src/Asset/Environment/Transformer/SlugTransformer.php, src/Asset/Environment/Transformer/StaticTransformer.php, src/Asset/Environment/Transformer/TransformerInterface.php, src/Asset/Environment/Transformer/VersionTransformer.php
Since PHP 8.0, the `static` return type annotation can be used. It is now added to the `TransformerInterface::fromArray()` method to properly reflect the existing annotation.
=> [BUGFIX] Use static return for `TransformerInterface::fromArray`

src/Command/ConfigAssetsCommand.php, src/Config/Config.php, src/Config/Parser/Parser.php, src/Json/SchemaValidator.php, tests/Unit/Json/SchemaValidatorTest.php
With this PR, the `SchemaValidator::validate()` method now expects a valid `Config` object instead of a resolved array. Additionally, the `Config` object now implements `JsonSerializable` and can therefore passed to the `json_encode` method as-is.
=> [!!!][FEATURE] Expect config object in `SchemaValidator::validate()`

docs/usage/cli-config-assets.md, src/Command/BaseAssetsCommand.php, src/Command/ConfigAssetsCommand.php
Normally, it's not desired to process all placeholder values in asset configurations when reading or validating configuration. Therefore, this is now disabled by default, but can be explicitly enabled by passing the `--process-values` option to the `config` command.
=> [!!!][FEATURE] Do not process values by default in `config` command

src/Command/FetchAssetsCommand.php, src/Handler/AssetHandler.php
Since the introduction of union types, we can now limit the return types of `AssetHandler::handle()` to match the actual return types, namely `ExistingAsset` and `ProcessedAsset`. With this modification, an additional safety check in the `fetch` command is removed altogether.
=> [!!!][BUGFIX] Return only existing and processed assets from handler

config/services.php, config/services.yaml, config/services_test.php, config/services_test.yaml, docs/config/full-reference.md, docs/migration.md, docs/usage/api-usage.md, resources/configuration.schema.json, src/Command/FetchAssetsCommand.php, src/Handler/AssetHandler.php, src/Handler/HandlerFactory.php, tests/Unit/Fixtures/Classes/DummyHandler.php, tests/Unit/Handler/AssetHandlerTest.php, tests/Unit/Handler/HandlerFactoryTest.php
With this PR, consumers can now provide custom handler implementations. For this, a `HandlerFactory` has been introduced with the default `AssetHandler` configured as type `default`. Custom handlers implementing the `HandlerInterface` can therefore be used within the asset handling process. For this, they must be explicitly configured in the asset definition:
```diff
{
+    "handler": "my-custom-handler",
"source": { /* ... */ },
"target": { /* ... */ }
}
```
=> [!!!][FEATURE] Allow custom handler implementations

src/Handler/AssetHandler.php, src/Handler/HandlerFactory.php, src/Processor/ProcessorFactory.php, src/Provider/ProviderFactory.php, tests/Unit/Fixtures/Classes/DummyProvider.php, tests/Unit/Handler/HandlerFactoryTest.php, tests/Unit/Processor/ProcessorFactoryTest.php, tests/Unit/Provider/ProviderFactoryTest.php
With this PR, all classes implementing the `ChattyInterface` now make use of the provided `OutputAwareTrait` in order to streamline handling of output-aware classes. Additionally, this fixes an issue introduced with #12 where the original output is not passed to the final providers and processors.
=> [BUGFIX] Streamline output handling of chatty classes

src/Value/Placeholder/EnvironmentVariableProcessor.php, tests/Unit/Value/Placeholder/EnvironmentVariableProcessorTest.php
Prior to this PR, only the first environment variable placeholder was matched and all subsequent placeholders were replaced with the resolved environment variable of the first match. With this PR, `preg_match_all` is now used instead of `preg_match` in order to properly process all environment variable placeholders.
Resolves: #16
=> [BUGFIX] Handle multiple environment variable placeholders

.github/workflows/release.yaml
The phar artifact generated by the release workflow is now restored in the expected build path.
=> [BUGFIX] Restore phar artifact in correct path

src/Config/Initialization/Step/SourceConfigStep.php, tests/Unit/Config/Initialization/Step/SourceConfigStepTest.php
The `source.version` config was forgotten when implementing the source config step. It is now added.
=> [BUGFIX] Include version in source config initialization step

docs/migration.md, resources/configuration.schema.json, tests/Unit/Command/ConfigAssetsCommandTest.php
This PR partially reverts changes introduced with 1.0.0 regarding required `type` configuration for `source` and `target` definitions: Since the library ships default providers and processors, we use those types as fallback and make the `type` configuration optional.
Resolves: #22
=> [BUGFIX] Respect default source and target types

resources/configuration.schema.json, src/Asset/Definition/Vcs.php, tests/Unit/Asset/Definition/AssetDefinitionFactoryTest.php, tests/Unit/Asset/Definition/VcsTest.php, tests/Unit/Vcs/GitlabVcsProviderTest.php, tests/Unit/Vcs/VcsProviderFactoryTest.php
With 1.0.0, declaring a `type` for the `vcs` definition was made a required configuration. However, both the schema and the appropriate `Vcs` definition class still provided `gitlab` as default type in case no `type` was set. This is now fixed and the `vcs` definition does no longer provide a default type.
=> [BUGFIX] Follow-up: Require a type when building a `Vcs` object

src/Asset/Environment/Map/Pair.php, tests/Unit/Asset/Environment/EnvironmentResolverTest.php
It was discovered that the current implementation to detect matching branches is not strong enough. The version pattern `*.*.*` matches on all branches, therefore the default value "stable" is never considered.
=> [BUGFIX] Harden match for environment mapping branches

.github/workflows/tests.yaml
Sometimes the required `CC_TEST_REPORTER_ID` secret for CodeClimate is not available, e.g. within forks. Since codecov already handles coverage reports, we only run CodeClimate if the appropriate secret exists.
=> [BUGFIX] Skip codeclimate coverate report if secret is not available

src/Command/FetchAssetsCommand.php, tests/Unit/Command/FetchAssetsCommandTest.php
A duplicate assertion in `FetchAssetsCommandTest` is fixed to catch a successful case:
https://github.com/CPS-IT/frontend-asset-handler/blob/a4fcc69069950ce0c8325171fd8b37d95f9c0c83/tests/Unit/Command/FetchAssetsCommandTest.php#L108-L109
=> [BUGFIX] fix duplicate test assertion

src/Command/FetchAssetsCommand.php, tests/Unit/Command/FetchAssetsCommandTest.php
This PR changes the output for already existing revisions in the `FetchAssetsCommand` console command. No further configuration is required.
It is this author's humble opinion that it should not be an error when a revision was previously downloaded and won't be re-downloaded hence. However, while agreeing that a success message would encourage users to draw a wrong conclusion a `warning` level is suggested. Consistently, no error is printed at the end of (potentially) all fetch attempts. The suggestion to use the `-f` parameter to enforce a re-download is kept.
=> [FEATURE] lower error level to warning for already downloaded revisions

src/Command/FetchAssetsCommand.php, tests/Unit/Command/FetchAssetsCommandTest.php, tests/Unit/Fixtures/Classes/DummyHandler.php
The selected strategy is currently not passed on if the `fetch` command is executed together with `--failsafe` and the requested download fails. This is now fixed and the strategy is always passed to the next iteration.
=> [BUGFIX] Pass on strategy when fetching assets for fallback environment

.gitattributes
The following files and directories will no longer be exported:
* `.ddev` directory
* `config/services_test.*` files
* `CONTRIBUTING.md` file
=> [BUGFIX] Exclude various dev-only files from being exported

config/services.yaml
Factories are part of the public API and therefore must be publicly accessible. All internal factories are still private. Additionally, the config parser (which is part of the public API as well) is now a public service.
=> [BUGFIX] Assure public API classes are publicly available services

docs/config/target.md, src/Config/ConfigFacade.php, src/Config/Initialization/Step/ConfigFileStep.php, src/DependencyInjection/ContainerFactory.php, src/Helper/FilesystemHelper.php, src/Traits/TargetPathBuilderTrait.php, tests/Unit/Helper/FilesystemHelperTest.php
When relative paths are passed and resolved using `FilesystemHelper::resolveRelativePath()`, the base path determination logic was currently not always equal. Sometimes, the current working directory was used, whereas other code parts used the project root path.
In order to streamline the logic, the path of a project's `composer.json` is now always used as base path, unless the current execution context is a running PHAR file. In this case, the current working directory is still used as fallback.
=> [BUGFIX] Streamline base path handling for relative paths

src/Vcs/GitlabVcsProvider.php
VCS providers are designed to work either on a standalone basis or by construction from a valid `Vcs` object. Therefore, all available properties must be settable for both construction strategies. Since this was not available for the standalone strategy in `GitlabVcsProvider`, all properties are now promoted via the class constructor.
=> [BUGFIX] Promote all properties in `GitlabVcsProvider`

composer.json, composer.lock, docs/components/vcs-providers.md, phpstan.neon, src/Config/Initialization/Step/VcsConfigStep.php, src/Vcs/GithubVcsProvider.php, tests/Build/Stubs/GraphQL/QueryBuilder.stub, tests/Unit/Config/Initialization/Step/VcsConfigStepTest.php, tests/Unit/Vcs/GithubVcsProviderTest.php
This PR adds a new VCS provider `github`. It requires the following configuration:
- `access-token` with token scope `repo`
- `repository` in the format `<owner>/<name>`, e.g. `CPS-IT/frontend-asset-handler`
=> [FEATURE] Add support for GitHub as VCS provider

composer.json, composer.lock, src/Vcs/GithubVcsProvider.php
This reverts commit 9f03ae874ead18a3bdf193baa225343b244bddf0 and requires at least Rector 0.14.7 which fixed the mentioned bug with rectorphp/rector-src#3030.
=> [TASK] Revert "[BUGFIX] Disable invalid behavior of ReadOnlyPropertyRector"

.github/workflows/tests.yaml
The dependencies for PHP 8.2 are quite stable, so there's no more need to ignore platform requirements.
=> [TASK] Do not ignore platform reqs for PHP 8.2 in CI

src/Helper/FilesystemHelper.php, src/Provider/HttpFileProvider.php, tests/Unit/Helper/FilesystemHelperTest.php, tests/Unit/Provider/HttpFileProviderTest.php
The public API of `FilesystemHelper` is now extended by a new method `createTemporaryFile`. It may be used to create files only relevant during script execution. All temporary files will be removed on script shutdown.
This is a breaking change as the handling of temporary files within `HttpFileProvider` is now extracted to the new API method within `FilesystemHelper`, leading to a function signature change in the class constructor.
=> [!!!][FEATURE] Add temporary file creation method to FilesystemHelper

src/Console/Application.php, src/Helper/FilesystemHelper.php, tests/Unit/Helper/FilesystemHelperTest.php
This PR adds a new method `getWorkingDirectory()` to the public API of `FilesystemHelper`. It resolves to the path containing the project's root `composer.json` or – when executed as PHAR file – the current working directory.
=> [FEATURE] Introduce `FilesystemHelper::getWorkingDirectory()` method

src/Provider/HttpFileProvider.php, tests/Unit/Provider/HttpFileProviderTest.php
This PR fixes a regression introduced with #106 where source file extensions are not properly maintained, e.g. if the file extension is `.tar.gz`.
Resolves: #129
=> [BUGFIX] Assure source file extension is properly maintained

src/Asset/Definition/AssetDefinition.php
Asset definitions are JSON-encoded when requesting their string representation, e.g. in various exception classes. Since they should represent its original configuration as much as possible, slashes must not be escaped.
=> [TASK] Unescape slashes when JSON-encoding asset definition

src/Command/InitConfigCommand.php, src/Config/Initialization/Step/HandlerConfigStep.php, src/Config/Initialization/Step/SourceConfigStep.php, src/Config/Initialization/Step/TargetConfigStep.php, src/Config/Initialization/Step/VcsConfigStep.php
This PR improves user-oriented output of the `init` command when running in non-interactive mode. In addition, it fixes a bug where omitting the optional VCS type led to a validation error in non-interactive mode.
=> [BUGFIX] Improve stability of `init` command in non-interactive mode

.github/workflows/cgl.yaml, composer.json, composer.lock, src/Exception/MissingPackageException.php, src/Vcs/GithubVcsProvider.php, tests/Unit/Exception/MissingPackageExceptionTest.php, tests/Unit/Vcs/GithubVcsProviderTest.php
The `gmostafa/php-graphql-client` package is not required in most cases, because it's only used within the VCS provider `github`. Since VCS providers are optional and most probably `gitlab` is used, we no longer require end-users to install this package. Instead, it is now suggested during `composer install` and `composer update` for the outlined case.
Resolves: #207
=> [!!!][TASK] Move `gmostafa/php-graphql-client` to package suggestions

docs/components/providers.md, resources/configuration.schema.json, src/Asset/Definition/Source.php, src/Config/Initialization/Step/BaseStep.php, src/Config/Initialization/Step/SourceConfigStep.php, src/Exception/FilesystemFailureException.php, src/Provider/LocalPathProvider.php, tests/Unit/Config/Initialization/Step/SourceConfigStepTest.php, tests/Unit/Provider/LocalPathProviderTest.php
This PR introduces a new provider `local`. It can be used to define a local file as Frontend asset source file.
Example configuration:
```json
{
"frontend-assets": [
{
"source": {
"type": "local",
"command": "tar -czvf '{url}' -C '{cwd}/frontend' 'dist'",
"url": "{temp}.tar.gz"
},
"target": {
"type": "archive",
"path": "public/assets",
"base": "dist/"
}
}
]
}
```
Resolves: #82
=> [FEATURE] Introduce local file provider

CONTRIBUTING.md, composer.json
This PR harmonizes the usage of CGL scripts:
- `lint` scripts no longer fix CGL issues, but only print them to the console (dry-run mode)
- `fix` scripts actually fix CGL issues (like done before with `lint:<program>:fix`)
=> [TASK] Streamline `lint` and `fix` CGL scripts

renovate.json
This PR modifies the `renovate.json` file to use shared config presets from `CPS-IT/renovate-config` repository.
=> [TASK] Use Renovate config presets from CPS config repository

src/Helper/FilesystemHelper.php, src/Provider/HttpFileProvider.php, tests/Unit/Helper/FilesystemHelperTest.php
It turns out, there are still problems with detecting the correct file extension of gzipped files. In order to stabilize file extension determination, a new helper method `FilesystemHelper::getFileExtension()` is introduced. It supports normal files and gzipped files.
=> [BUGFIX] Correctly determine file extension of gzipped files

.github/workflows/tests.yaml
Since PHP 8.3 was released in a stable version, there's no need to mark it as "experimental" any longer. Hence, this PR removes the "experimental" flag from test workflow.
=> [TASK] Don't treat PHP 8.3 as "experimental" any longer

.github/workflows/cgl.yaml, .github/workflows/tests.yaml, CONTRIBUTING.md, README.md, renovate.json
This PR drops usage of Git Flow and therefore drops usage of `develop` as default development branch. Instead, `main` is now used instead.
=> [TASK] Drop Git Flow and use main branch as default branch

resources/configuration.schema.json, src/Config/Parser/ServicesParser.php, src/DependencyInjection/ContainerFactory.php, tests/Unit/Config/Parser/ServicesParserTest.php
This PR adds the already supported `services` object to configuration schema. In addition, parsing of service configuration files is simplified.
=> [TASK] Add `services` to schema and simplify parsing

resources/configuration.schema.json
This PR updates the configuration schema to only allow the configured `frontend-assets` and `services` properties on root level.
=> [BUGFIX] Disallow additional properties on root scope of config files

.github/workflows/cgl.yaml, .github/workflows/tests.yaml
This PR switches PHP version to PHP 8.3 in Test and CGL workflows.
=> [TASK] Use PHP 8.3 in workflows

src/Console/Application.php
This change adds an integer return type hint to the doRun method in the Application class. This ensures the declaration is compatible with the symfony console input interface.
=> [BUGFIX] Add return type hint to doRun method

docs/config/environments.md, docs/migration.md, src/Asset/Environment/Map/MapFactory.php, tests/src/Asset/Definition/AssetDefinitionFactoryTest.php, tests/src/Asset/Environment/EnvironmentResolverTest.php, tests/src/Asset/Environment/Map/MapFactoryTest.php
The default environment map has changed. All branches except `renovate/*` now use or fall back to their slug representation.
=> [!!!][FEATURE] Use more generic default for environment map
